apiVersion: v1
kind: Service
metadata:
  name: my-tweet-app-svc
  namespace: my-tweet-app
  labels:
    app: my-tweet-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 32519
  selector:
    app: my-tweet-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tweet-app
  namespace: my-tweet-app
  labels:
    app: my-tweet-app
spec:
  selector:
    matchLabels:
      app: my-tweet-app
  replicas: 2
  template:
    metadata:
      labels:
        app: my-tweet-app
    spec:
      containers:
      - name: my-tweet-app
        image: dubbrzr/my-tweet-app-lacework:latest
        ports:
        - containerPort: 32519
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
